### ISSUE TITLE
Automate Data Collection to work with different 3D models

### ISSUE THREAD

**Issue by DanielCoelho112** [DanielCoelho112/localization_end_to_end#70]
Current Data Collection was implemented based on 024 model, which means it has a lot of hard-coded hyperparameters, such as the size of the room, and minimum and maximum angles... We should associate each 3D model to a YAML file with all hyperparameters, and then the Data Collection can use the values of the file.

**Comment by DanielCoelho112** [comment]
Hi @miguelriemoliveira and @pmdjdias,

now, when running the data collection command, we should include a config file with the specification of the collection:

    rosrun localbot_core data_collector --mode automatic_path --seq seq1006 -nf 1000 -mc 'my_room_024.yaml'


my_room_024.yaml:
```yaml

volume:
  position:
    xmin: 1.5
    xmax: 3.5
    ymin: 1.5
    ymax: 5.0
    zmin: -0.5
    zmax: 0.5
  angles:
    rxmin: -0.52
    rxmax: 0.52
    rymin: -0.52
    rymax: 0.52
    rzmin: 0
    rzmax: 6.28
light:
  light_names: 
  - 'user_point_light_0'
  - 'user_point_light_1'
  - 'user_point_light_2'
  - 'user_point_light_3'
  - 'user_point_light_4'
  - 'user_point_light_5'
  att_initial: 1.0
  att_min: 0.1
  att_max: 1.0
```
 
In this file we have to specify the boundaries of the position and rotation angles. In addition, we can also specify the lights names as well as the maximum and minimum lighting intensity.
